### ISSUE TITLE
[BUG] FlightTracker unable to start after upgrading from v1 to v2

### ISSUE THREAD

**Issue by julesfarrow** [ColinWaddell/its-a-plane-python#88]
### FlightTracker version

v2.4.0

### Platform

Raspberry Pi 4

### Operating system

Bookworm

### Data source

FlightRadar24 (online)

### What happened?

When attempting to upgrade from v1 to v2, I followed these steps:

```
sudo systemctl stop FlightTracker.service
git fetch --all
git checkout main
git pull
source env/bin/activate
pip install -r platforms/pi/requirements.txt 
sudo systemctl start FlightTracker.service
```

The service fails to start

Upon running

`python flight-tracker.py
`

this error shows:

`  File "/home/pi/FlightTracker/flight-tracker.py", line 14, in <module>
    from setup.configuration import CONFIG_PATH, Config
  File "/home/pi/FlightTracker/setup/configuration.py", line 30, in <module>
    platformdirs.user_data_dir(APP_NAME, APP_AUTHOR, ensure_exists=True)
TypeError: user_data_dir() got an unexpected keyword argument 'ensure_exists'`

This error can be resolved by removing the 'ensure_exists = True' parameter from Line 30 of setup/configuration.py

Starting FlightTracker manually or as a service then works correctly.

### Steps to reproduce

as above

### Relevant log output

```shell

```

### Debug config

```json

```

**Comment by ColinWaddell** [comment]
Hmm. Weird one. I wonder if the platformdir package needs updated at your
side? Either way, thanks for the report and I’ll roll this into the next
update


--
Colin
colinwaddell.com <https://www.colinwaddell.com>

**Comment by julesfarrow** [comment]
No worries at all.

I'm not sure the configuration file conversion has worked either. Still have config.py in the top-level dir and no json equivalent. Web interface doesn't seem to be able to save & restart.

I'm going to just do a fresh install but I'll copy the folder if you want me to check anything further, happy to help.

**Comment by ColinWaddell** [comment]
Run:

python flight-tracker.py data

It’ll show you where your config.json is

Probably going to be in .local/share/FlightTracker

I don’t keep anything in the src folder any more as I want the repo to be immutable


--
Colin
colinwaddell.com <https://www.colinwaddell.com>

**Comment by julesfarrow** [comment]
Cheers - that would explain it!

I've done a fresh install and no complaints about the original error from Line 30 of setup/configuration.py

Still having issues with web interface being able to edit & save changes, but suspect that's a separate issue.

**Comment by ColinWaddell** [comment]
When in doubt, nuke the card and rerun the installer script


--
Colin
colinwaddell.com <https://www.colinwaddell.com>

**Comment by ColinWaddell** [comment]
Oh. And if nothings saving can I ask, are you updating the admin password?
Not much works till you change it from “flighttracker

--
Colin
colinwaddell.com <https://www.colinwaddell.com>

**Comment by julesfarrow** [comment]
Correct again - nuked the old config file, set password & we're back in business. Much appreciated!

**Comment by ColinWaddell** [comment]
Happy to help!

Word of warning though. The lookup-service we use for flight info when not
using FR24 has gone down today so your box might show “unknown” for a lot
of flights


--
Colin
colinwaddell.com <https://www.colinwaddell.com>
